name: Saving Task

on:
  schedule:
    - cron: '0 18 */7 * *'
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          cache: 'pip'
          cache-dependency-path: 'scripts/requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f scripts/requirements.txt ]; then pip install -r scripts/requirements.txt; fi

      - name: Run task
        run: python scripts/task.py

      - name: Set current time
        id: time
        run: echo "NOW=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update: ${{ env.NOW }}"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
